heat_template_version: 2014-10-16

description: Gabarit pour déployer un seul serveur web

parameters:

  image:
    type: string
    description: Image utilisee pour les serveurs
    default: INF4410-Ubuntu-trusty-mini
    constraints:
      - custom_constraint: glance.image

  flavor:
    type: string
    description: Flavor utilisee par les serveurs
    default: INF4410-mini
    constraints:
      - custom_constraint: nova.flavor

  subnet_id:
    type: string
    description: Sous-reseau dans lequel le load balancer sera situe
    default: 6579eb07-88c3-4707-9c6e-ab90a78cca02
    constraints:
      - custom_constraint: neutron.subnet

  key_name:
    type: string
    description: Clé privée
    default: TP3
    constraints:
      - custom_constraint: nova.keypair

  network:
    type: string
    description: nom du sous-réseau
    default: inf4410-net

  ext_subnet_id:
    type: string
    description: id du sous-réseau externe
    default: 0c3b1354-d3d5-4fec-86d3-19d4d1f13785

  scriptlink:
    type: string
    description: lien vers le script python
    default: https://raw.githubusercontent.com/houssemmh/INF8480-TP3/master/server.py

resources:
  server:
    type: OS::Nova::Server
    properties:
      name: WebServer
      key_name: { get_param: key_name }
      image: { get_param: image }
      flavor: { get_param: flavor }
      networks: [{network: {get_param: network} }]
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #!/bin/bash
            wget scriptlink
            python server.py
          params:
            scriptlink: {get_param: scriptlink}

  floatingip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: { get_param: ext_subnet_id }

  floatingipassociation:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: floatingip }
      server_id: { get_resource: server }
